# REAL-YML
spring:
  application:
    name: teamA_BE

  servlet:  # multipart 관련 설정
    multipart:
      max-file-size: 30000000 # 파일 최대 사이즈 : 바이트, 30MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 클래스 이름
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql # 사용할 데이터베이스 유형 지정 (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate에서 사용할 MySQL 방언(dialect) 설정
    show-sql: true # 실행된 SQL 쿼리를 콘솔에 출력할지 여부 설정
    hibernate:
      ddl-auto: create # 애플리케이션 실행 시 데이터베이스 스키마의 상태를 설정
    properties:
      hibernate:
        format_sql: true # 출력되는 SQL 쿼리를 보기 좋게 포맷팅

  cloud: # S3 설정
    aws:
      credentials:
        access-key: "IAM Access Key"
        secret-key: "IAM Secret Key"
      region:
        static: ap-northeast-2
      s3:
        bucket: "버킷 이름"
      stack:
        auto: false

logging:
  level:
    org.hibernate: DEBUG
